import Head from 'next/head'
import Layout from '../components/layout'

export default function Home() {
  return (
    <>

        <Head>
          <title>gaizka.me</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout></Layout>

    </>

  )
}
