import Head from 'next/head'
import Navbar from '../components/navbar'
import Hero from '../components/Hero'

export default function Home() {
  return (
    <>

      <Head>
        <title>gaizka.me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />

    </>

  )
}
